-- Generated by scripts/generate_tensor_expansion.py; all proofs checked by Lean.
import K4Ramsey.IntegerTensorK4

namespace K4Ramsey.IntegerTensorK4

section Expansion
variable {B L : Type*} [Fintype B] [Fintype L]
variable (W : Kernel B) (D : Kernel (B × L))
variable (hW : transpose (liftBase (L := L) W) = liftBase W)
variable (hD : transpose D = D)
variable (hc : ∀ i j y, ∑ x : L, D (i,x) (j,y) = 0)
include hW hD hc
set_option linter.unusedSectionVars false

private theorem term_0 : sum (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) = sum (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) := by
  rfl

private theorem term_1 : sum D (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) = 0 := by
  exact centered_leaf_zero D (liftBase W) (liftBase W) (liftBase W) hc W W

private theorem term_2 : sum (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) (liftBase W) (liftBase W) hc W W

private theorem term_3 : sum D D (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  exact centered_leaf_zero D D (liftBase W) (liftBase W) hc W W

private theorem term_4 : sum (liftBase (L := L) W) (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) (liftBase W) (liftBase W) hc W W

private theorem term_5 : sum D (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) D (liftBase W) hc W W

private theorem term_6 : sum (liftBase (L := L) W) D D (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  conv_lhs => rw [swap01]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) D (liftBase W) hc W W

private theorem term_7 : sum D D D (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  exact centered_leaf_zero D D D (liftBase W) hc W W

private theorem term_8 : sum (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) (liftBase W) (liftBase W) hc W W

private theorem term_9 : sum D (liftBase (L := L) W) (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W) = 0 := by
  exact centered_leaf_zero D D (liftBase W) (liftBase W) hc W W

private theorem term_10 : sum (liftBase (L := L) W) D (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D D (liftBase W) (liftBase W) hc W W

private theorem term_11 : sum D D (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W) = sum D D (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W) := by
  rfl

private theorem term_12 : sum (liftBase (L := L) W) (liftBase (L := L) W) D D (liftBase (L := L) W) (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) (liftBase W) D hc W W

private theorem term_13 : sum D (liftBase (L := L) W) D D (liftBase (L := L) W) (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  conv_lhs => rw [swap01]; simp only [hW, hD]
  exact centered_leaf_zero D D (liftBase W) D hc W W

private theorem term_14 : sum (liftBase (L := L) W) D D D (liftBase (L := L) W) (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D D (liftBase W) D hc W W

private theorem term_15 : sum D D D D (liftBase (L := L) W) (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  conv_lhs => rw [swap01]; simp only [hW, hD]
  exact centered_leaf_zero D D D D hc W W

private theorem term_16 : sum (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) D (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) (liftBase W) (liftBase W) hc W W

private theorem term_17 : sum D (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) D (liftBase (L := L) W) = 0 := by
  exact centered_leaf_zero D (liftBase W) D (liftBase W) hc W W

private theorem term_18 : sum (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W) D (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) (liftBase W) D hc W W

private theorem term_19 : sum D D (liftBase (L := L) W) (liftBase (L := L) W) D (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  conv_lhs => rw [swap01]; simp only [hW, hD]
  exact centered_leaf_zero D D (liftBase W) D hc W W

private theorem term_20 : sum (liftBase (L := L) W) (liftBase (L := L) W) D (liftBase (L := L) W) D (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D D (liftBase W) (liftBase W) hc W W

private theorem term_21 : sum D (liftBase (L := L) W) D (liftBase (L := L) W) D (liftBase (L := L) W) = sum D D (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W) := by
  conv_lhs => rw [swap23]; simp only [hW, hD]

private theorem term_22 : sum (liftBase (L := L) W) D D (liftBase (L := L) W) D (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  conv_lhs => rw [swap01]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) D D hc W W

private theorem term_23 : sum D D D (liftBase (L := L) W) D (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  conv_lhs => rw [swap01]; simp only [hW, hD]
  exact centered_leaf_zero D D D D hc W W

private theorem term_24 : sum (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) D D (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  conv_lhs => rw [swap01]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) D (liftBase W) hc W W

private theorem term_25 : sum D (liftBase (L := L) W) (liftBase (L := L) W) D D (liftBase (L := L) W) = 0 := by
  exact centered_leaf_zero D D D (liftBase W) hc W W

private theorem term_26 : sum (liftBase (L := L) W) D (liftBase (L := L) W) D D (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D D (liftBase W) D hc W W

private theorem term_27 : sum D D (liftBase (L := L) W) D D (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  conv_lhs => rw [swap01]; simp only [hW, hD]
  exact centered_leaf_zero D D D D hc W W

private theorem term_28 : sum (liftBase (L := L) W) (liftBase (L := L) W) D D D (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D D (liftBase W) D hc W W

private theorem term_29 : sum D (liftBase (L := L) W) D D D (liftBase (L := L) W) = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  conv_lhs => rw [swap01]; simp only [hW, hD]
  exact centered_leaf_zero D D D D hc W W

private theorem term_30 : sum (liftBase (L := L) W) D D D D (liftBase (L := L) W) = sum (liftBase (L := L) W) D D D D (liftBase (L := L) W) := by
  rfl

private theorem term_31 : sum D D D D D (liftBase (L := L) W) = sum D D D D D (liftBase (L := L) W) := by
  rfl

private theorem term_32 : sum (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) D = 0 := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) (liftBase W) (liftBase W) hc W W

private theorem term_33 : sum D (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) D = 0 := by
  exact centered_leaf_zero D (liftBase W) (liftBase W) D hc W W

private theorem term_34 : sum (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) D = 0 := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) D (liftBase W) hc W W

private theorem term_35 : sum D D (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) D = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  exact centered_leaf_zero D D (liftBase W) D hc W W

private theorem term_36 : sum (liftBase (L := L) W) (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W) D = 0 := by
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) D (liftBase W) hc W W

private theorem term_37 : sum D (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W) D = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) D D hc W W

private theorem term_38 : sum (liftBase (L := L) W) D D (liftBase (L := L) W) (liftBase (L := L) W) D = sum D D (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W) := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  conv_lhs => rw [swap23]; simp only [hW, hD]

private theorem term_39 : sum D D D (liftBase (L := L) W) (liftBase (L := L) W) D = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  exact centered_leaf_zero D D D D hc W W

private theorem term_40 : sum (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) D (liftBase (L := L) W) D = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) D (liftBase W) hc W W

private theorem term_41 : sum D (liftBase (L := L) W) (liftBase (L := L) W) D (liftBase (L := L) W) D = 0 := by
  exact centered_leaf_zero D D (liftBase W) D hc W W

private theorem term_42 : sum (liftBase (L := L) W) D (liftBase (L := L) W) D (liftBase (L := L) W) D = 0 := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D D D (liftBase W) hc W W

private theorem term_43 : sum D D (liftBase (L := L) W) D (liftBase (L := L) W) D = 0 := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  conv_lhs => rw [swap01]; simp only [hW, hD]
  exact centered_leaf_zero D D D D hc W W

private theorem term_44 : sum (liftBase (L := L) W) (liftBase (L := L) W) D D (liftBase (L := L) W) D = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) D D hc W W

private theorem term_45 : sum D (liftBase (L := L) W) D D (liftBase (L := L) W) D = sum (liftBase (L := L) W) D D D D (liftBase (L := L) W) := by
  conv_lhs => rw [swap12]; simp only [hW, hD]

private theorem term_46 : sum (liftBase (L := L) W) D D D (liftBase (L := L) W) D = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D D D D hc W W

private theorem term_47 : sum D D D D (liftBase (L := L) W) D = sum D D D D D (liftBase (L := L) W) := by
  conv_lhs => rw [swap12]; simp only [hW, hD]

private theorem term_48 : sum (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) D D = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) D (liftBase W) hc W W

private theorem term_49 : sum D (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) D D = 0 := by
  exact centered_leaf_zero D (liftBase W) D D hc W W

private theorem term_50 : sum (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W) D D = 0 := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D (liftBase W) D D hc W W

private theorem term_51 : sum D D (liftBase (L := L) W) (liftBase (L := L) W) D D = sum (liftBase (L := L) W) D D D D (liftBase (L := L) W) := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]

private theorem term_52 : sum (liftBase (L := L) W) (liftBase (L := L) W) D (liftBase (L := L) W) D D = 0 := by
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D D D (liftBase W) hc W W

private theorem term_53 : sum D (liftBase (L := L) W) D (liftBase (L := L) W) D D = 0 := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D D D D hc W W

private theorem term_54 : sum (liftBase (L := L) W) D D (liftBase (L := L) W) D D = 0 := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D D D D hc W W

private theorem term_55 : sum D D D (liftBase (L := L) W) D D = sum D D D D D (liftBase (L := L) W) := by
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]

private theorem term_56 : sum (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) D D D = sum D D (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W) := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  conv_lhs => rw [swap23]; simp only [hW, hD]

private theorem term_57 : sum D (liftBase (L := L) W) (liftBase (L := L) W) D D D = 0 := by
  exact centered_leaf_zero D D D D hc W W

private theorem term_58 : sum (liftBase (L := L) W) D (liftBase (L := L) W) D D D = 0 := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D D D D hc W W

private theorem term_59 : sum D D (liftBase (L := L) W) D D D = sum D D D D D (liftBase (L := L) W) := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]

private theorem term_60 : sum (liftBase (L := L) W) (liftBase (L := L) W) D D D D = 0 := by
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]
  exact centered_leaf_zero D D D D hc W W

private theorem term_61 : sum D (liftBase (L := L) W) D D D D = sum D D D D D (liftBase (L := L) W) := by
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]

private theorem term_62 : sum (liftBase (L := L) W) D D D D D = sum D D D D D (liftBase (L := L) W) := by
  conv_lhs => rw [swap12]; simp only [hW, hD]
  conv_lhs => rw [swap01]; simp only [hW, hD]
  conv_lhs => rw [swap23]; simp only [hW, hD]
  conv_lhs => rw [swap12]; simp only [hW, hD]

private theorem term_63 : sum D D D D D D = sum D D D D D D := by
  rfl

/-- Exact centered-refinement identity. All repeated coarse and fine
indices are included; no injectivity assumption is used. -/
theorem centered_expansion :
    colorSum (fun u v => liftBase W u v + D u v) =
      sum (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W) (liftBase (L := L) W)
      + 4 * sum D D (liftBase (L := L) W) D (liftBase (L := L) W) (liftBase (L := L) W)
      + 3 * sum (liftBase (L := L) W) D D D D (liftBase (L := L) W)
      + 6 * sum D D D D D (liftBase (L := L) W)
      + sum D D D D D D := by
  change sum (fun u v => liftBase W u v + D u v)
    (fun u v => liftBase W u v + D u v)
    (fun u v => liftBase W u v + D u v)
    (fun u v => liftBase W u v + D u v)
    (fun u v => liftBase W u v + D u v)
    (fun u v => liftBase W u v + D u v) = _
  simp only [add01, add02, add03, add12, add13, add23]
  simp only [term_1 W D hW hD hc, term_2 W D hW hD hc, term_3 W D hW hD hc, term_4 W D hW hD hc, term_5 W D hW hD hc, term_6 W D hW hD hc, term_7 W D hW hD hc, term_8 W D hW hD hc, term_9 W D hW hD hc, term_10 W D hW hD hc, term_12 W D hW hD hc, term_13 W D hW hD hc, term_14 W D hW hD hc, term_15 W D hW hD hc, term_16 W D hW hD hc, term_17 W D hW hD hc, term_18 W D hW hD hc, term_19 W D hW hD hc, term_20 W D hW hD hc, term_21 W D hW hD hc, term_22 W D hW hD hc, term_23 W D hW hD hc, term_24 W D hW hD hc, term_25 W D hW hD hc, term_26 W D hW hD hc, term_27 W D hW hD hc, term_28 W D hW hD hc, term_29 W D hW hD hc, term_32 W D hW hD hc, term_33 W D hW hD hc, term_34 W D hW hD hc, term_35 W D hW hD hc, term_36 W D hW hD hc, term_37 W D hW hD hc, term_38 W D hW hD hc, term_39 W D hW hD hc, term_40 W D hW hD hc, term_41 W D hW hD hc, term_42 W D hW hD hc, term_43 W D hW hD hc, term_44 W D hW hD hc, term_45 W D hW hD hc, term_46 W D hW hD hc, term_47 W D hW hD hc, term_48 W D hW hD hc, term_49 W D hW hD hc, term_50 W D hW hD hc, term_51 W D hW hD hc, term_52 W D hW hD hc, term_53 W D hW hD hc, term_54 W D hW hD hc, term_55 W D hW hD hc, term_56 W D hW hD hc, term_57 W D hW hD hc, term_58 W D hW hD hc, term_59 W D hW hD hc, term_60 W D hW hD hc, term_61 W D hW hD hc, term_62 W D hW hD hc]
  all_goals ring

end Expansion
end K4Ramsey.IntegerTensorK4
