#!/usr/bin/env python3
"""Embed an AutoLab-style two-color certificate as Lean UInt64 rows."""

from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer

from k4_ramsey.engine import read_certificate

app = typer.Typer(pretty_exceptions_enable=False)


def main() -> None:
    app()


@app.command()
def generate_certificate(
    solution: Path,
    output: Path,
    namespace: Annotated[str, typer.Option()],
) -> None:
    """Embed a validated unit-weight graph as Lean UInt64 rows."""

    data = read_certificate(solution)
    rows = data["red_rows"]
    n = len(rows)

    packed_rows = []
    for row in rows:
        words = []
        for start in range(0, n, 64):
            word = sum(
                (bit == "1") << offset
                for offset, bit in enumerate(row[start : start + 64])
            )
            words.append(f"(0x{word:016x} : UInt64)")
        packed_rows.append("  #[" + ", ".join(words) + "],")
    body = "\n".join(packed_rows)
    source = f"""-- Generated by `scripts/generate_lean_certificate.py`; do not hand-edit.
import K4Ramsey.Counting.Multiplicity

set_option maxRecDepth 100000

namespace K4Ramsey.{namespace}

def redRows : Array BitRow := #[
{body}
]

end K4Ramsey.{namespace}
"""
    output.write_text(source, encoding="utf-8")


if __name__ == "__main__":
    main()
