"""Generate ordinary Lean proofs for all 64 six-edge expansion terms.

Python only chooses vertex permutations. Every choice is checked by Lean using
the sum-reindexing and leaf-cancellation theorems, never by an oracle.
"""
from collections import deque
from pathlib import Path

EDGES = [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]
SWAPS = [(0, 1), (1, 2), (2, 3)]


def permute(mask, swap):
    p = list(range(4))
    a, b = swap
    p[a], p[b] = p[b], p[a]
    return sum(1 << k for k, (i, j) in enumerate(EDGES)
               if mask & (1 << EDGES.index(tuple(sorted((p[i], p[j]))))))


def args(mask):
    return " ".join("D" if mask & (1 << k) else "(liftBase (L := L) W)" for k in range(6))


def path_to(mask, predicate):
    q = deque([(mask, [])])
    seen = {mask}
    while q:
        m, path = q.popleft()
        if predicate(m):
            return m, path
        for swap in SWAPS:
            nxt = permute(m, swap)
            if nxt not in seen:
                seen.add(nxt)
                q.append((nxt, path + [swap]))
    raise ValueError(mask)


def main():
    out = ["-- Generated by scripts/generate_tensor_expansion.py; all proofs checked by Lean.",
           "import K4Ramsey.Counting.TensorK4", "", "namespace K4Ramsey.TensorK4", "",
           "section Expansion", "variable {B L : Type*} [Fintype B] [Fintype L]",
           "variable (W : Kernel B) (D : Kernel (B × L))",
           "variable (hW : transpose (liftBase (L := L) W) = liftBase W)",
           "variable (hD : transpose D = D)",
           "variable (hc : ∀ i j y, ∑ x : L, D (i,x) (j,y) = 0)",
           "include hW hD hc", "set_option linter.unusedSectionVars false", ""]
    counts = {0: 0, 11: 0, 30: 0, 31: 0, 63: 0}
    for mask in range(64):
        degrees = [sum(bool(mask & (1 << k)) for k, e in enumerate(EDGES) if v in e)
                   for v in range(4)]
        leaf = 1 in degrees
        if leaf:
            target, path = path_to(mask, lambda m: m & 7 == 1)
            rhs = "0"
        else:
            target, path = path_to(mask, lambda m: m in counts)
            counts[target] += 1
            rhs = "sum " + args(target)
        out += [f"private theorem term_{mask} : sum {args(mask)} = {rhs} := by"]
        for a, b in path:
            out += [f"  conv_lhs => rw [swap{a}{b}]; simp only [hW, hD]"]
        if leaf:
            tail = " ".join("D" if target & (1 << k) else "(liftBase W)" for k in (3, 4, 5))
            out += [f"  exact centered_leaf_zero D {tail} hc W W"]
        elif not path:
            out += ["  rfl"]
        out += [""]
    assert counts == {0: 1, 11: 4, 30: 3, 31: 6, 63: 1}, counts
    out += ["/-- Exact centered-refinement identity. All repeated coarse and fine",
            "indices are included; no injectivity assumption is used. -/",
            "theorem centered_expansion :",
            "    Graphon.colorSum (fun u v => liftBase W u v + D u v) =",
            "      sum " + args(0),
            "      + 4 * sum " + args(11),
            "      + 3 * sum " + args(30),
            "      + 6 * sum " + args(31),
            "      + sum " + args(63) + " := by",
            "  change sum (fun u v => liftBase W u v + D u v)",
            "    (fun u v => liftBase W u v + D u v)",
            "    (fun u v => liftBase W u v + D u v)",
            "    (fun u v => liftBase W u v + D u v)",
            "    (fun u v => liftBase W u v + D u v)",
            "    (fun u v => liftBase W u v + D u v) = _",
            "  simp only [add01, add02, add03, add12, add13, add23]"]
    # Lean omits unused section parameters from each generated theorem. Supply
    # hypotheses via `simp`'s discharge mechanism rather than guessing binders.
    names = ", ".join(f"term_{m} W D hW hD hc" for m in range(64) if m not in counts)
    out += [f"  simp only [{names}]",
            "  all_goals ring", "", "end Expansion", "end K4Ramsey.TensorK4", ""]
    Path("lean/K4Ramsey/Counting/CenteredExpansion.lean").write_text("\n".join(out))
    integer_source = "\n".join(out).replace("K4Ramsey.TensorK4", "K4Ramsey.IntegerTensorK4")
    integer_source = integer_source.replace("K4Ramsey.Counting.TensorK4", "K4Ramsey.Counting.IntegerTensorK4")
    integer_source = integer_source.replace("Graphon.colorSum", "colorSum")
    Path("lean/K4Ramsey/Counting/IntegerCenteredExpansion.lean").write_text(integer_source)


if __name__ == "__main__":
    main()
