#!/usr/bin/env python3
"""Embed an AutoLab-style two-color certificate as Lean UInt64 rows."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("solution", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--namespace", required=True)
    args = parser.parse_args()

    data = json.loads(args.solution.read_text(encoding="utf-8"))
    rows = data["red_rows"]
    n = len(rows)
    weights = data.get("weights")
    if weights != [1] * n or any(type(w) is not int for w in weights):
        raise ValueError("this Lean checker currently requires unit integer weights")
    if n == 0 or any(len(row) != n or set(row) - {"0", "1"} for row in rows):
        raise ValueError("red_rows must be a nonempty square binary matrix")
    if any(rows[i][j] != rows[j][i] for i in range(n) for j in range(n)):
        raise ValueError("red_rows must be symmetric")
    if any(rows[i][i] != "0" for i in range(n)):
        raise ValueError("this Lean checker currently requires a blue diagonal")

    packed_rows = []
    for row in rows:
        words = []
        for start in range(0, n, 64):
            word = sum((bit == "1") << offset for offset, bit in enumerate(row[start:start + 64]))
            words.append(f"(0x{word:016x} : UInt64)")
        packed_rows.append("  #[" + ", ".join(words) + "],")
    body = "\n".join(packed_rows)
    source = f'''-- Generated by `scripts/generate_lean_certificate.py`; do not hand-edit.
import K4Ramsey.Multiplicity

set_option maxRecDepth 100000

namespace K4Ramsey.{args.namespace}

def redRows : Array BitRow := #[
{body}
]

end K4Ramsey.{args.namespace}
'''
    args.output.write_text(source, encoding="utf-8")


if __name__ == "__main__":
    main()
